Style/Documentation:
  Enabled: false
  
Style/MixinUsage:
  Enabled: false
Layout/EmptyLineBetweenDefs:
  Enabled: true
  AllowBeforeFirstMethod: false  # Optional: Enforces no space before the first method
